// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Core>>
abstract class Core implements RustOpaqueInterface {
  /// Todos os contatos já pareados.
  Future<List<ContactDto>> listContacts();

  /// Os 145 bytes do QR Code desta identidade.
  Future<Uint8List> myQrPayload();

  /// Abre (criando na primeira execução) a identidade e o banco cifrado em
  /// `app_dir` — o diretório de dados privados do app, não um segredo.
  static Future<Core> open({required String appDir}) =>
      RustLib.instance.api.crateFfiCoreCoreOpen(appDir: appDir);

  /// Valida o payload lido pela câmera e persiste o contato.
  Future<ContactDto> pairFromQr({required List<int> payload});

  /// Safety number entre esta identidade e um contato já pareado.
  Future<SafetyNumberDto> safetyNumber({required List<int> contactDeviceId});
}
