// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// Erro devolvido por uma chamada FFI.
enum FfiError {
  /// Comprimento errado, versão desconhecida ou campo malformado.
  qrMalformed,

  /// A assinatura do payload não confere.
  qrBadSignature,

  /// O QR lido é o desta própria identidade.
  selfPairing,

  /// Chave X25519 de ordem baixa — sinal de payload forjado, não de leitura
  /// ruim. Merece mensagem própria na UI (ver armadilha 4 do relatório).
  forgedKey,

  /// Falha ao abrir, ler ou gravar no banco cifrado.
  storeFailure,

  /// Nenhum contato com o `device_id` informado.
  contactNotFound,

  /// Qualquer outra falha interna, sem informação útil para a UI.
  internal,
}
