// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Prefixa `envelope` com seu comprimento em big-endian, para envio pelo
/// socket TCP local.
Future<Uint8List> frameForLocalSocket({required List<int> envelope}) =>
    RustLib.instance.api.crateFfiFramingFrameForLocalSocket(envelope: envelope);

/// Extrai o próximo quadro completo de `buffer`, se já tiver chegado por
/// inteiro, devolvendo o quadro extraído e o restante do buffer.
///
/// `extracted: None` significa "ainda não chegaram bytes suficientes" — quem
/// chama só precisa acumular mais bytes lidos do socket em `remaining` e
/// tentar de novo. Erro (comprimento anunciado maior que o cabível) é
/// tratado como `FfiError::Internal`: um peer que anuncia isso está sendo
/// hostil ou está corrompido, e a única resposta correta (armadilha da Fase
/// 6, §4) é derrubar a conexão — não tentar de novo sobre o mesmo buffer.
Future<(Uint8List?, Uint8List)> extractFrameFromLocalSocketBuffer({
  required List<int> buffer,
}) => RustLib.instance.api.crateFfiFramingExtractFrameFromLocalSocketBuffer(
  buffer: buffer,
);
