// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Atraso a aplicar antes do próximo envio, em milissegundos — normal
/// truncada em [5, 25] ms (§6.5). Chamar de novo a cada mensagem: o valor
/// não deve ser reaproveitado entre envios.
Future<BigInt> sampleJitterDelayMs() =>
    RustLib.instance.api.crateFfiJitterSampleJitterDelayMs();
