// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_identity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Um contato pareado, como a UI precisa exibi-lo.
class ContactDto {
  final Uint8List deviceId;
  final Uint8List signingPubkey;
  final Uint8List dhPubkey;
  final PlatformInt64 pairedAtUnixSecs;
  final String? nickname;
  final bool isVerified;

  const ContactDto({
    required this.deviceId,
    required this.signingPubkey,
    required this.dhPubkey,
    required this.pairedAtUnixSecs,
    this.nickname,
    required this.isVerified,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      signingPubkey.hashCode ^
      dhPubkey.hashCode ^
      pairedAtUnixSecs.hashCode ^
      nickname.hashCode ^
      isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          signingPubkey == other.signingPubkey &&
          dhPubkey == other.dhPubkey &&
          pairedAtUnixSecs == other.pairedAtUnixSecs &&
          nickname == other.nickname &&
          isVerified == other.isVerified;
}

/// Estado de entrega de uma mensagem de saída — espelha
/// `store::messages::DeliveryState`. `Delivered`/`Failed` ainda não são
/// produzidos por nenhum código desta fase (reservados para quando
/// `MSG_RECEIPT` e relato de falha de transporte existirem).
enum DeliveryStateDto { pending, sent, delivered, failed }

/// `BeaconID`s de descoberta local para um contato — `docs/protocol.md` §9.1.
/// Os dois lados calculam o mesmo `advertise_beacon`, ao contrário dos
/// tópicos de sinalização (que têm direção).
class DiscoveryBeaconsDto {
  /// Beacon para anunciar agora — só a época corrente.
  final Uint8List advertiseBeacon;

  /// Os três beacons aceitáveis para procurar — épocas
  /// anterior/atual/seguinte.
  final List<Uint8List> scanBeacons;

  const DiscoveryBeaconsDto({
    required this.advertiseBeacon,
    required this.scanBeacons,
  });

  @override
  int get hashCode => advertiseBeacon.hashCode ^ scanBeacons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveryBeaconsDto &&
          runtimeType == other.runtimeType &&
          advertiseBeacon == other.advertiseBeacon &&
          scanBeacons == other.scanBeacons;
}

/// Uma oferta de arquivo recebida, pronta para a UI perguntar "aceitar?" —
/// hoje sempre aceita automaticamente (sem fluxo de aceite/recusa ainda,
/// ver relatório da Fase 4).
class FileOfferDto {
  final Uint8List fileId;
  final String name;
  final BigInt fileSize;

  const FileOfferDto({
    required this.fileId,
    required this.name,
    required this.fileSize,
  });

  @override
  int get hashCode => fileId.hashCode ^ name.hashCode ^ fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileOfferDto &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          name == other.name &&
          fileSize == other.fileSize;
}

/// Uma mensagem recebida e decifrada, pronta para a UI.
class IncomingMessageDto {
  /// `None` só para `MSG_TYPING` — indicador efêmero, nunca persistido
  /// (`docs/protocol.md` §6.2).
  final PlatformInt64? messageId;
  final String body;
  final bool isTyping;
  final PlatformInt64 receivedAtUnixSecs;

  const IncomingMessageDto({
    this.messageId,
    required this.body,
    required this.isTyping,
    required this.receivedAtUnixSecs,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      body.hashCode ^
      isTyping.hashCode ^
      receivedAtUnixSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IncomingMessageDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          body == other.body &&
          isTyping == other.isTyping &&
          receivedAtUnixSecs == other.receivedAtUnixSecs;
}

/// Resultado de alimentar um pacote do canal `file` — Fase 5, D17:
/// `Core::ingest_incoming_wire_bytes` já descobre sozinho a qual
/// transferência o pacote pertence (o `file_id` vem em claro no próprio
/// pacote), então devolve qual foi para quem chama saber que progresso
/// atualizar.
class IngestedChunkDto {
  final Uint8List fileId;
  final TransferProgressDto progress;

  const IngestedChunkDto({required this.fileId, required this.progress});

  @override
  int get hashCode => fileId.hashCode ^ progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestedChunkDto &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          progress == other.progress;
}

/// Direção de uma mensagem persistida — espelha `store::messages::Direction`,
/// sem reexportar o tipo interno diretamente na fronteira FFI.
enum MessageDirectionDto { outgoing, incoming }

/// Uma mensagem já persistida, pronta para a tela de chat renderizar — texto
/// e nota de voz na mesma timeline (Fase 5: unificar as duas era decisão do
/// usuário, não escolha técnica deste código).
class MessageDto {
  final PlatformInt64 id;
  final MessageDirectionDto direction;
  final MessageKindDto kind;

  /// Corpo de texto — só significa algo quando `kind == Text`. Vazio para
  /// `VoiceNote` (o conteúdo real é `audio_file_id`, resolvido à parte
  /// via `Core::pending_audio_offers`/`Core::received_voice_notes`).
  final String body;

  /// `file_id` da transferência de áudio — só preenchido quando
  /// `kind == VoiceNote`.
  final Uint8List? audioFileId;
  final DeliveryStateDto deliveryState;
  final PlatformInt64 createdAtUnixSecs;
  final bool isEphemeral;
  final PlatformInt64? replyToId;
  final bool viewOnce;
  final List<String> reactions;

  const MessageDto({
    required this.id,
    required this.direction,
    required this.kind,
    required this.body,
    this.audioFileId,
    required this.deliveryState,
    required this.createdAtUnixSecs,
    required this.isEphemeral,
    this.replyToId,
    required this.viewOnce,
    required this.reactions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      audioFileId.hashCode ^
      deliveryState.hashCode ^
      createdAtUnixSecs.hashCode ^
      isEphemeral.hashCode ^
      replyToId.hashCode ^
      viewOnce.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          kind == other.kind &&
          body == other.body &&
          audioFileId == other.audioFileId &&
          deliveryState == other.deliveryState &&
          createdAtUnixSecs == other.createdAtUnixSecs &&
          isEphemeral == other.isEphemeral &&
          replyToId == other.replyToId &&
          viewOnce == other.viewOnce &&
          reactions == other.reactions;
}

/// Distingue uma mensagem de texto de uma nota de voz na timeline única —
/// Fase 5. Espelha os dois valores de `packet_type` que hoje entram em
/// `messages` (`MSG_TEXT`/`AUDIO_CHUNK`); qualquer outro `packet_type`
/// nunca é persistido nesta tabela (`store::messages::reject_typing` e o
/// resto do desenho da Fase 3).
enum MessageKindDto { text, voiceNote, file }

/// O safety number entre a identidade local e um contato, nas duas
/// representações da spec §3.3.
class SafetyNumberDto {
  /// 12 grupos de 5 dígitos, separados por espaço.
  final String digits;

  /// 6 palavras da lista BIP-39 PT-BR, separadas por espaço.
  final String words;

  const SafetyNumberDto({required this.digits, required this.words});

  @override
  int get hashCode => digits.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyNumberDto &&
          runtimeType == other.runtimeType &&
          digits == other.digits &&
          words == other.words;
}

/// Uma mensagem de saída já persistida como `pending`, e cifrada se a sessão
/// já estava pronta na hora da chamada.
class SealedMessageDto {
  /// `id` na tabela `messages` — usado depois em `Core::mark_message_sent`.
  final PlatformInt64 messageId;

  /// `None` quando a sessão ainda não está `Established`: a mensagem já
  /// está persistida como `pending`, mas não há nada para enviar ainda —
  /// o outbox (Fase 3, F6) tenta de novo via `Core::flush_pending` assim
  /// que a sessão ficar pronta.
  final Uint8List? bytes;

  const SealedMessageDto({required this.messageId, this.bytes});

  @override
  int get hashCode => messageId.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SealedMessageDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          bytes == other.bytes;
}

/// Como [`SendFileStartedDto`], para `Core::start_send_audio` — carrega
/// também o `message_id` da linha `Pending` já inserida na timeline única
/// (Fase 5), para quem chama poder marcá-la `Sent` depois
/// (`Core::mark_message_sent`).
class SendAudioStartedDto {
  final Uint8List fileId;
  final Uint8List sealedMetadata;
  final PlatformInt64 messageId;

  const SendAudioStartedDto({
    required this.fileId,
    required this.sealedMetadata,
    required this.messageId,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^ sealedMetadata.hashCode ^ messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendAudioStartedDto &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          sealedMetadata == other.sealedMetadata &&
          messageId == other.messageId;
}

/// Uma transferência de envio recém-iniciada — `Core::start_send_file`.
class SendFileStartedDto {
  /// Identifica a transferência nas chamadas seguintes
  /// (`next_outgoing_wire_chunk`, `transfer_progress`).
  final Uint8List fileId;

  /// Corpo do `FILE_METADATA` já selado — mandar pelo canal `control`.
  final Uint8List sealedMetadata;

  /// `id` na tabela `messages` — usado depois em `Core::mark_message_sent`.
  final PlatformInt64 messageId;

  const SendFileStartedDto({
    required this.fileId,
    required this.sealedMetadata,
    required this.messageId,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^ sealedMetadata.hashCode ^ messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendFileStartedDto &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          sealedMetadata == other.sealedMetadata &&
          messageId == other.messageId;
}

/// Estado de uma sessão, sem nenhum dos campos criptográficos de
/// `viska_proto::session::Session` — só o que a UI precisa para decidir o que
/// mostrar (indicador de conexão, botão de retry).
enum SessionStateKind {
  /// Handshake em andamento — nem INIT nem RESP concluídos ainda.
  handshaking,

  /// Pronta para cifrar/decifrar mensagens.
  established,

  /// Precisa de uma sessão nova (`Core::ensure_session` de novo).
  failed,
}

/// Status de uma sessão, devolvido por `Core::ensure_session`.
class SessionStatusDto {
  final SessionStateKind state;

  /// `true` quando o contador de envio já cruzou o limiar de segurança —
  /// a sessão ainda funciona para decifrar, mas `encrypt_outgoing` vai
  /// recusar mensagens novas.
  final bool needsRehandshake;

  /// Bytes de handshake a publicar via sinalização — presente sempre que
  /// formos iniciador e ainda não tivermos recebido a RESP, `None` em
  /// qualquer outro caso (respondedor, sessão já estabelecida, ou
  /// falhada). Chamar `ensure_session` várias vezes nesse intervalo
  /// devolve os mesmos bytes todas as vezes, nunca uma INIT nova — mais
  /// de uma parte do app pode precisar deles em momentos diferentes (ver
  /// `Session::pending_outgoing_handshake`).
  final Uint8List? outgoingHandshake;

  const SessionStatusDto({
    required this.state,
    required this.needsRehandshake,
    this.outgoingHandshake,
  });

  @override
  int get hashCode =>
      state.hashCode ^ needsRehandshake.hashCode ^ outgoingHandshake.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          needsRehandshake == other.needsRehandshake &&
          outgoingHandshake == other.outgoingHandshake;
}

/// Tópicos de sinalização para um contato — `docs/protocol.md` §8.1.
class SignalingTopicsDto {
  /// Tópico para publicar agora — só a época corrente, nossa direção.
  final String publishTopic;

  /// Os três tópicos para assinar — épocas anterior/atual/seguinte, na
  /// direção do par (a oposta da nossa).
  final List<String> subscribeTopics;

  const SignalingTopicsDto({
    required this.publishTopic,
    required this.subscribeTopics,
  });

  @override
  int get hashCode => publishTopic.hashCode ^ subscribeTopics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignalingTopicsDto &&
          runtimeType == other.runtimeType &&
          publishTopic == other.publishTopic &&
          subscribeTopics == other.subscribeTopics;
}

/// Progresso de uma transferência em andamento, de qualquer lado.
class TransferProgressDto {
  final int blocksDone;
  final int totalBlocks;
  final BigInt bytesDone;
  final bool isComplete;

  const TransferProgressDto({
    required this.blocksDone,
    required this.totalBlocks,
    required this.bytesDone,
    required this.isComplete,
  });

  @override
  int get hashCode =>
      blocksDone.hashCode ^
      totalBlocks.hashCode ^
      bytesDone.hashCode ^
      isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgressDto &&
          runtimeType == other.runtimeType &&
          blocksDone == other.blocksDone &&
          totalBlocks == other.totalBlocks &&
          bytesDone == other.bytesDone &&
          isComplete == other.isComplete;
}
