// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_identity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Um contato pareado, como a UI precisa exibi-lo.
class ContactDto {
  final Uint8List deviceId;
  final Uint8List signingPubkey;
  final Uint8List dhPubkey;
  final PlatformInt64 pairedAtUnixSecs;
  final String? nickname;

  const ContactDto({
    required this.deviceId,
    required this.signingPubkey,
    required this.dhPubkey,
    required this.pairedAtUnixSecs,
    this.nickname,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      signingPubkey.hashCode ^
      dhPubkey.hashCode ^
      pairedAtUnixSecs.hashCode ^
      nickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          signingPubkey == other.signingPubkey &&
          dhPubkey == other.dhPubkey &&
          pairedAtUnixSecs == other.pairedAtUnixSecs &&
          nickname == other.nickname;
}

/// O safety number entre a identidade local e um contato, nas duas
/// representações da spec §3.3.
class SafetyNumberDto {
  /// 12 grupos de 5 dígitos, separados por espaço.
  final String digits;

  /// 6 palavras da lista BIP-39 PT-BR, separadas por espaço.
  final String words;

  const SafetyNumberDto({required this.digits, required this.words});

  @override
  int get hashCode => digits.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyNumberDto &&
          runtimeType == other.runtimeType &&
          digits == other.digits &&
          words == other.words;
}
